param(
    [string]$ShaclPath = (Join-Path (Join-Path $PSScriptRoot "..\..") (Join-Path "models" "establishment-details-data-quality-shacl.ttl")),
    [string]$OutputPath = (Join-Path (Join-Path $PSScriptRoot "..") (Join-Path (Join-Path "content" "models") "establishment-data-quality-rules.md"))
)

$ErrorActionPreference = "Stop"

$resolvedShaclPath = Resolve-Path -LiteralPath $ShaclPath
$ttl = Get-Content -LiteralPath $resolvedShaclPath -Raw

function Get-FirstStringLiteral {
    param([string]$Block, [string]$Predicate)
    $pattern = [regex]::Escape($Predicate) + '\s+"((?:[^"\\]|\\.)*)"'
    $match = [regex]::Match($Block, $pattern)
    if ($match.Success) { return $match.Groups[1].Value }
    return ""
}

function Get-TargetClass {
    param([string]$Block)
    $match = [regex]::Match($Block, 'sh:targetClass\s+([\w:]+)')
    if ($match.Success) { return $match.Groups[1].Value }
    return ""
}

function Get-ConstraintSummary {
    param([string]$PropertyBlock)

    $datatypeMatch    = [regex]::Match($PropertyBlock, 'sh:datatype\s+([\w:]+)')
    $minIncMatch      = [regex]::Match($PropertyBlock, 'sh:minInclusive\s+([\d.]+)')
    $maxIncMatch      = [regex]::Match($PropertyBlock, 'sh:maxInclusive\s+([\d.]+)')
    $minCountMatch    = [regex]::Match($PropertyBlock, 'sh:minCount\s+(\d+)')
    $maxCountMatch    = [regex]::Match($PropertyBlock, 'sh:maxCount\s+(\d+)')

    $parts = @()

    if ($datatypeMatch.Success)  { $parts += "Datatype: ``$($datatypeMatch.Groups[1].Value)``" }

    if ($minIncMatch.Success -and $maxIncMatch.Success) {
        $parts += "Range: $($minIncMatch.Groups[1].Value) - $($maxIncMatch.Groups[1].Value)"
    } elseif ($minIncMatch.Success) {
        $parts += "Minimum: $($minIncMatch.Groups[1].Value)"
    } elseif ($maxIncMatch.Success) {
        $parts += "Maximum: $($maxIncMatch.Groups[1].Value)"
    }

    $min = if ($minCountMatch.Success) { [int]$minCountMatch.Groups[1].Value } else { $null }
    $max = if ($maxCountMatch.Success) { [int]$maxCountMatch.Groups[1].Value } else { $null }

    if ($null -ne $min -and $min -eq 1 -and $null -ne $max -and $max -eq 1) {
        $parts += "Required - exactly one"
    } elseif ($null -ne $min -and $min -eq 1) {
        $parts += "Required - at least one"
    } elseif ($null -ne $max -and $max -eq 1) {
        $parts += "At most one"
    }

    return ($parts -join "; ")
}

function Get-PathDisplay {
    param([string]$PropertyBlock)
    $match = [regex]::Match($PropertyBlock, 'sh:path\s+([\w:<>/#]+)')
    if ($match.Success) {
        $raw = $match.Groups[1].Value
        # Expand well-known prefixed names for readability
        $raw = $raw -replace '^rdf:value$', 'rdf:value'
        return "``$raw``"
    }
    return ""
}

function Escape-MarkdownTableCell {
    param([string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value)) { return "" }
    return $Value -replace '\|', '\|'
}

# Extract each sh:NodeShape block
$shapeMatches = [regex]::Matches(
    $ttl,
    '(?ms)^(epr:\w+)\r?\n\s+a sh:NodeShape\s*;(.*?)(?=^epr:|\z)'
)

if ($shapeMatches.Count -eq 0) {
    throw "No sh:NodeShape blocks found in $resolvedShaclPath"
}

$lines = @(
    "# Establishment Data Quality Rules",
    "",
    "This page is generated from ``models/establishment-details-data-quality-shacl.ttl`` during the site build. Do not edit this file directly.",
    "",
    "These are value-level constraints on establishment records - datatypes, numeric ranges and cardinality rules. They are separate from the [field applicability rules](../establishment-type-field-rules/), which define which fields are required, optional or not applicable per establishment type.",
    "",
    "Each section applies to instances of a specific ontology class. When an establishment record includes a field of that type, the values in that field must satisfy all listed constraints.",
    "",
    "| Constraint | Meaning |",
    "| --- | --- |",
    "| Datatype | The value must be of this XML Schema datatype |",
    "| Range | The value must fall within this inclusive numeric range |",
    "| Required - exactly one | The field must be present with exactly one value |",
    "| At most one | The field may be present but must not have more than one value |",
    ""
)

foreach ($shapeMatch in $shapeMatches) {
    $localName = $shapeMatch.Groups[1].Value
    $block     = $shapeMatch.Groups[2].Value

    $label       = Get-FirstStringLiteral -Block $block -Predicate 'rdfs:label'
    $comment     = Get-FirstStringLiteral -Block $block -Predicate 'rdfs:comment'
    $targetClass = Get-TargetClass -Block $block

    if ([string]::IsNullOrWhiteSpace($label)) { $label = $localName -replace '^epr:', '' }

    $lines += '---'
    $lines += ''
    $lines += "## $label"
    $lines += ''

    if (-not [string]::IsNullOrWhiteSpace($targetClass)) {
        $lines += "Applies to instances of **``$targetClass``**."
        $lines += ''
    }

    if (-not [string]::IsNullOrWhiteSpace($comment)) {
        $lines += $comment
        $lines += ''
    }

    $propertyMatches = [regex]::Matches($block, '(?s)sh:property\s+\[\s*(.*?)\s*\]')

    if ($propertyMatches.Count -gt 0) {
        $lines += '| Field | Path | Constraints | Message |'
        $lines += '| --- | --- | --- | --- |'

        foreach ($propMatch in $propertyMatches) {
            $propBlock   = $propMatch.Groups[1].Value
            $fieldName   = Get-FirstStringLiteral -Block $propBlock -Predicate 'sh:name'
            $message     = Get-FirstStringLiteral -Block $propBlock -Predicate 'sh:message'
            $pathDisplay = Get-PathDisplay -PropertyBlock $propBlock
            $constraints = Get-ConstraintSummary -PropertyBlock $propBlock

            if (-not [string]::IsNullOrWhiteSpace($fieldName)) {
                $lines += "| $(Escape-MarkdownTableCell $fieldName) | $pathDisplay | $(Escape-MarkdownTableCell $constraints) | $(Escape-MarkdownTableCell $message) |"
            }
        }
        $lines += ''
    }
}

$lines += '---'
$lines += ''
$lines += "Source: [``models/establishment-details-data-quality-shacl.ttl``](https://github.com/DFE-Digital/education-provider-registry-docs/blob/main/models/establishment-details-data-quality-shacl.ttl)"

$outputDir = Split-Path -Path $OutputPath -Parent
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
Set-Content -LiteralPath $OutputPath -Value $lines -Encoding UTF8

Write-Host "Generated $($shapeMatches.Count) shape sections in $OutputPath"


