-- PostgreSQL loader for the complete local-authority reference fixture.
-- The fixture is generated by local-authorities-from-bau.sql.

BEGIN;

CREATE TEMP TABLE source_local_authority_fixture (
    code text,
    name text,
    jurisdiction_name text
) ON COMMIT DROP;

\copy source_local_authority_fixture FROM '__FIXTURE_PATH__' WITH (FORMAT csv, HEADER true, DELIMITER '|', NULL 'NULL')

INSERT INTO establishment.local_authority (
    code, name, local_authority_jurisdiction_id
)
SELECT NULLIF(BTRIM(s.code), '')::integer,
       s.name,
       j.local_authority_jurisdiction_id
FROM source_local_authority_fixture AS s
JOIN establishment.local_authority_jurisdiction AS j
  ON j.name = NULLIF(BTRIM(s.jurisdiction_name), '')
WHERE NULLIF(BTRIM(s.code), '') IS NOT NULL
  AND NULLIF(BTRIM(s.code), '')::integer IS NOT NULL
  AND NULLIF(BTRIM(s.code), '')::integer <> 0
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    local_authority_jurisdiction_id = EXCLUDED.local_authority_jurisdiction_id;

-- These records are deliberately synthetic. Every identifying value is
-- prefixed with FAKE so they cannot be mistaken for source contact data.
DELETE FROM establishment.local_authority_contact
WHERE contact_role LIKE 'FAKE%';

WITH first_ten AS (
    SELECT local_authority_id,
           ROW_NUMBER() OVER (ORDER BY code) AS sequence_number
    FROM establishment.local_authority
    ORDER BY code
    LIMIT 10
)
INSERT INTO establishment.local_authority_contact (
    local_authority_id,
    contact_email,
    contact_first_name,
    contact_last_name,
    contact_title,
    contact_phone,
    contact_role,
    is_current
)
SELECT local_authority_id,
       'FAKE.local-authority-contact-' || LPAD(sequence_number::text, 2, '0') || '@example.invalid',
       'FAKE Contact ' || LPAD(sequence_number::text, 2, '0'),
       'FAKE Local Authority',
       'FAKE Contact Title',
       'FAKE-0000-' || LPAD(sequence_number::text, 2, '0'),
       'FAKE Local Authority Contact ' || LPAD(sequence_number::text, 2, '0'),
       true
FROM first_ten;

COMMIT;
